export enum OpenAIModel {
  GPT3_5_TURBO = 'gpt-3.5-turbo',
  GPT4_TURBO = 'gpt-4-turbo',
  GPT4_32K_TURBO = 'gpt-4-32k-turbo',
  GPT4_1 = 'gpt-4.1',
  GPT4_1_MINI = 'gpt-4.1-mini',
  GPT4_1_NANO = 'gpt-4.1-nano',
  GPT5 = 'gpt-5',
  GPT5_THINKING = 'gpt-5-thinking',
  GPT5_THINKING_MINI = 'gpt-5-thinking-mini',
  GPT5_THINKING_NANO = 'gpt-5-thinking-nano',
  GPT5_MAIN = 'gpt-5-main',
  GPT5_MAIN_MINI = 'gpt-5-main-mini',
  GPT3_5_TURBO_INSTRUCT = 'gpt-3.5-turbo-instruct',
  TEXT_DAVINCI_003 = 'text-davinci-003',
  TEXT_DAVINCI_002 = 'text-davinci-002',
  CODE_DAVINCI_002 = 'code-davinci-002',
  CODE_CUSHMAN_001 = 'code-cushman-001',
}
